### PR TITLE
Remove HTML requirement

### PR DESCRIPTION
**Pull request by Nikita240**
There is no reason to require users to include the `<div>`'s on their page when it can simply be automatically added with javascript.

I made `breakpoints` an object based associative array with the data `alias: domelement`, where `domelement` gets appended to the body upon initialization.

### CODE REVIEW

**Comment by maciej-gurban** [comment]
Hi, thanks for your contribution, Nikita. Should have been done awhile ago already. I'll try to test and merge in the next few days. 

Any reasons you've chosen $.each over native forEach? There doesn't seem to be much benefit to it.

**Comment by Nikita240** [comment]
@maciej-gurban yes there is a good reason. The `forEach` loop is only capable of iterating over normal arrays. It has no way of passing the "key" to the callback. The `alias` passed in the `$.each` is actually the key in the associative array, not the value.

**Comment by maciej-gurban** [comment]
Missed that. Thanks for clarification.

P.S. You went medieval on these white spaces ;)

**Comment by Nikita240** [comment]
It wasn't me! I'm pretty sure Atom just auto removes white spaces on save.

**Comment by dclawson** [comment]
Hi @maciej-gurban. 

Is there any chance these pull requests could be merged into master? Both exactly what Im looking for.

Thanks

**Comment by maciej-gurban** [comment]
Done and done.

**Comment by dclawson** [comment]
:+1:

**Pull request merged**
