### PR TITLE
Added gulp with proper tooling

### PR DESCRIPTION
**Pull request by JuhQ**
The project was missing jshint and minification tools, even though minified version is available.

Added simple gulp setup to lint and minify code. Also added `src` folder from where distribution versions can be built.

### CODE REVIEW

**Comment by maciej-gurban** [comment]
Kiitos Juha!

It's a very valuable contribution! Could you make a PR against 'build-tools' branch? You've done a lot already, but would it possible to implement ESLint instead of JSHint?

**Comment by JuhQ** [comment]
@maciej-gurban I changed jshint to eslint, but you sure you want a new PR against `build-tools` branch?
Why not master?

**Comment by maciej-gurban** [comment]
Thanks!

Each feature gets its branch and when it's ready, gets merged into develop.
Develop is merged into master upon creating a "production" release, which
is then tagged and used by bower (and soon npm).

Just my internal process that avoids mistakes and merge conflicts.

**Comment by JuhQ** [comment]
Fair enough. I could also do the PR to develop branch

**Comment by maciej-gurban** [comment]
Either would be fine, but dedicated branch is preferred, since changes can be still made to it before the feature is considered 'done' and ready to be shipped.

**Comment by JuhQ** [comment]
Roger, opening new PR against `build-tools` branch

**Pull request closed without merging**
