### PR TITLE
Build tools

### PR DESCRIPTION
**Pull request by JuhQ**
Build tools with eslint, new PR against `build-tools` branch

See old PR #37

### CODE REVIEW

**Comment by maciej-gurban** [comment]
Thanks!

**Comment by JuhQ** [comment]
Excellent!

**Comment by JuhQ** [comment]
@maciej-gurban just came my mind that I forgot to add eslint preset file to this pr. As this has now been merged but it's still in your validation branch, you might want to add a some preset. Airbnb has a great one which complains about everything :D

https://www.npmjs.com/package/eslint-config-airbnb-base

**Comment by maciej-gurban** [comment]
I'm actually in the process of applying a similar (airbnb-based) preset into my two other projects. Boy, is that fun!

**Pull request merged**
